### ISSUE TITLE
Split code into different files

### ISSUE THREAD

**Issue by JayFoxRox** [zaps166/NFSIISE-CPP#2]
There's currently one huge C++ file.

I think it should be split into different files, so that `_bss` and `_data` are stored elsewhere or that code is split into functionality (in terms of what the game uses the functions for).

The C++ prologue for making the code work should also be split into a separate file, and the x86 instruction handler routines should also be moved into a different file.

This would aid with incremental builds and implementing https://github.com/zaps166/NFSIISE/issues/51. However, it will also make it easier to split legal / illegal parts of this project, and also make it easier for beginners to understand how this project works.

If done correctly, it will also allow viewing the code on GitHub (which currently stresses the file size limit) and also allow for a better collaborative workflow (with a cleaner git history).

**Comment by zaps166** [comment]
The CPP file is auto-generated (software is not public, it is written in C++/QtCore), so I must change the generator software, not the CPP file. Otherwise every ASM change won't be synced with CPP code automatically.

**Comment by JayFoxRox** [comment]
Even more important to split it then, so the generator output can remain untouched for most situations, but the surrounding ecosystem can be improved.

I've made a change to my local file to support existing native pointers when compiling as 64-bit (or other sizes):

```c++
  template<typename T>
  InlineVoid push32(const T val)
  {
    uintptr_t p = (uintptr_t)val;
    uintptr_t sign_bits = 0;
    if (!is_unsigned<T>::value) {
      sign_bits = (uintptr_t)-((p >> 31ull) & 1);
    }
    assert((p >> 32ull) == (sign_bits >> 32ull));
    esp -= 4;
    to32i(esp) = val;
  }
```

*(I have edited this code fragment, for non 64-bit compilation; I did not test this modified variant - check edit history for older version)*

However, I'm currently no longer working on it due to the legal issues with this submodule and use of pointers in arguments to almost all kernel functions (https://github.com/zaps166/NFSIISE/issues/48).

*I was mostly interested in bootstrapping using this module, and then moving to https://github.com/zaps166/NFSIISE/issues/50; however, as-is, this would take too much time and I have too many other existing projects.*
